service: sayit-backend
frameworkVersion: "2"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

package:
  patterns:
    - "!package-lock.json"
    - "!package.json"

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}

functions:
  startInputProcessing:
    handler: functions/start-input-processing.handler
    events:
      - s3: 
          bucket: sayit.input.${self:custom.stage}
          event: s3:ObjectCreated:*    
    environment:
      INPUT_BUCKET_NAME: sayit.input.${self:custom.stage}

  startTextAnalysis:
    handler: functions/start-text-analysis.handler

resources:
  Resources:
    VideosToMergeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "S"
          - AttributeName: isMerged
            AttributeType: "N"
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: sayit-videos-to-merged-table
        GlobalSecondaryIndexes:
          - IndexName: byIsMerged
            KeySchema:
              - AttributeName: isMerged
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
  Outputs:
    AwsRegion:
      Value: ${self:custom.region}